uint8 CLAMP_TO_EDGE=0
uint8 MIRRORED_REPEAT=1
uint8 REPEAT=2
# the name needs to be unique, it will overwrite same named textures otherwise.
string name
# TODO(lucasw) make Texture msg
sensor_msgs/Image image
uint8 wrap_s  # 0
uint8 wrap_t  # 0
bool remove  # false
---
string message  # ""
bool success  # False
